-- all libraries
-- generated by scripts/add_module.sh
-- other libraries are spilted by ';'
libs_string = ";"
    .. "allocator;"
    .. "endian;"
    .. "types;"
    .. "git2;"
    .. "string;"
    .. "array;"
    .. "expected;"
    .. "traits;"
